### ISSUE TITLE
Make Workers runtime error codes discoverable in search

### ISSUE THREAD

**Issue by harrishancock** [cloudflare/workers-docs#248]
It appears that the table here https://developers.cloudflare.com/workers/writing-workers/debugging-tips/ was never ported anywhere.

Also, I've seen 1025 used for rate limiting in the wild, but not sure where it came from. A free tier thing, maybe?

**Comment by EverlastingBugstopper** [comment]
I believe this has been documented here https://developers.cloudflare.com/workers/about/tips/debugging/

However, error codes are not discoverable by search

alt text: screenshot of developers.cloudflare.com/workers search "1101" with no results
![image](https://user-images.githubusercontent.com/9408157/66425770-12407c80-e9d6-11e9-81eb-87fb7fdfa8cf.png)

alt text: screenshot of developers.cloudflare.com/workers search "error" with no relevant results
![image](https://user-images.githubusercontent.com/9408157/66425825-2a180080-e9d6-11e9-98ee-69ac69509a3c.png)

**Comment by signalnerve** [comment]
This is fixed with the re-index of the site in https://github.com/algolia/docsearch-configs/pull/1071
