### ISSUE TITLE
Document DNS record requirement for zoned Workers scripts

### ISSUE THREAD

**Issue by signalnerve** [cloudflare/workers-docs#251]
Currently, deploying a Workers script to a zone requires a DNS record to be set, even if the user is attempting to build an "originless" application. My personal preference (specifically for subdomains, like `foo.cloudflare.com`) is to set a CNAME record to `@`, but we should document a) that this restriction exists, and b) the suggested record/configuration to unblock users

**Comment by adaptive** [comment]
This is an often asked question on Cloudflare Community.
For geo-agnostic workers, we recommend the use of `A 192.0.2.1`, this allows Cloudflare to infer that the worker is not location dependent.

[https://tools.ietf.org/html/rfc5737](https://tools.ietf.org/html/rfc5737)
