### ISSUE TITLE
Reference navigation tree missing on Web Standards page but not sibling pages

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/workers-docs#252]
When viewing e.g. the Fetch page, see that the Reference nav subtree is visible on the left:

![image](https://user-images.githubusercontent.com/154613/60293392-1c3de400-98ed-11e9-84ae-99055aa1de88.png)

Just above Fetch in the subtree, is a sibling page, Web Standards. Clicking that we see this:

![image](https://user-images.githubusercontent.com/154613/60293407-2233c500-98ed-11e9-958c-3e60cd3472b9.png)

For some reason on this page the subtree of Reference is missing.

In fact, for all of the other children of `Reference > Runtime > APIs`—Fetch, Fetch Event, Cache, Streams, Encoding, and Web Crypto—the subtree of Reference is visible.

**Comment by victoriabernard92** [comment]
No longer an issue since we turn like into a 2 level subpage i.e. `Runtime > APIs` turned into just `Runtime APIs`
![image](https://user-images.githubusercontent.com/7578652/69262322-e396f380-0b88-11ea-80e1-e1f45f32a958.png)
