### ISSUE TITLE
Document terraform tooling

### ISSUE THREAD

**Issue by signalnerve** [cloudflare/workers-docs#253]
The previous version of the docs had a fairly comprehensive page on tooling via [Terraform](https://developers.cloudflare.com/workers/deploying-workers/terraform/) - while we generally want people to use Wrangler, we should build a similar page to the [Serverless](https://workers.cloudflare.com/docs/reference/tooling/serverless/) page, which is pretty concise and makes it clear that tooling _does_ exist for it.

**Comment by EverlastingBugstopper** [comment]
https://www.terraform.io/docs/providers/cloudflare/guides/version-2-upgrade.html
