### ISSUE TITLE
Getting started 'hello-world' template example uses an invalid project name

### ISSUE THREAD

**Issue by cwndrws** [cloudflare/workers-docs#261]
The getting started docs have an example command for starting a project with the `hello-world` template:

```bash
 wrangler generate myApp https://github.com/cloudflare/worker-template 
```
but `myApp` is an invalid script name and wrangler uses the project name as the script name, so if you try to publish this project, it will fail with the following API error:

```
Error: ErrorMessage { msg: "Something went wrong! Status: 400 Bad Request, Details {\n  \"result\": null,\n  \"success\": false,\n  \"errors\": [\n    {\n      \"code\": 10016,\n      \"message\": \"workers.api.error.invalid_script_name\"\n    }\n  ],\n  \"messages\": []\n}\n" }
```

We should fix the docs and then fix wrangler to either validate the project name on init, or reformat it to be compliant (just lowercase in this case).

**Comment by victoriabernard92** [comment]
All templates now use `my-app`
