### ISSUE TITLE
Workers Site Header Disjoint from Overall Workers Experience 

### ISSUE THREAD

**Issue by remyguercio** [cloudflare/workers-docs#360]
Problem: Right now there is a disjoint experience between the marketing page(s) for Workers and the docs. There are also a number of links in the nav for Workers docs that don't apply to Workers developers. This leads to a subpar experience for users. 

I'd like to start to unify this experience for users by merging the nav bars between the sites.

**Comment by victoriabernard92** [comment]
Closing because will be addressed in the redesign
duplicate of https://github.com/cloudflare/workers-docs/issues/204
