### ISSUE TITLE
Wonky formatting in Cache API reference

### ISSUE THREAD

**Issue by harrishancock** [cloudflare/workers-docs#416]
It looks like the Cache.match() and Cache.put() options documentation gained some unruly formatting:

![Screenshot from 2019-09-26 16-17-51](https://user-images.githubusercontent.com/1030771/65731146-657f0a80-e079-11e9-970d-eefa757472d0.png)

- The `ignoreMethod` option for match() should be on its own line.
- The remainder of the match() documentation beginning "Unlike the browser Cache API ..." should not be in a code block.
- /optons/options/ in the put() section.
- The `ignoreMethod` option for put() should ideally not be in a code block, though that's just my arbitrary preference.

**Comment by adaptive** [comment]
fixed and merged #476

**Comment by harrishancock** [comment]
Thanks @adaptive!
