### ISSUE TITLE
Algolia issue

### ISSUE THREAD

**Issue by victoriabernard92** [cloudflare/workers-docs#435]
Aloglia is linking to tags on the home page that exist but not on the home page. 

Try typing in "routes" then click List Routes. 

You should be directed to 
https://developers.cloudflare.com/workers/tooling/api/routes/#list-routes
But instead are directed to 
https://developers.cloudflare.com/workers/#list-routes

Notice the `/tooling/api/routes/` is stripped

https://cl.ly/92027dcbfca8

**Comment by victoriabernard92** [comment]
From @xtuc 
On https://developers.cloudflare.com/workers. Search for `cf`
![Screenshot from 2019-10-11 15-19-48](https://user-images.githubusercontent.com/7578652/66660298-9aa76300-ec0a-11e9-860f-84d7b5a63df4.png)
Some results are outdated.

**Comment by signalnerve** [comment]
getting back up to speed on this, tracking some work/questions here https://github.com/algolia/docsearch-configs/pull/1071

**Comment by signalnerve** [comment]
This is fixed!
