### ISSUE TITLE
Add explanation regarding async/await and Promises with HTMLRewriter

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/workers-docs#438]
(link for internal context) https://chat.google.com/room/AAAAGX7FDAU/3i9wOoKxO88

> HTMLRewriter handlers can't be async. async functions return promises and the parser just throws them out and moves on - by the time the handler's code runs, its element references are invalid and unusable, because the parser's state has changed.

**Comment by maxiostro** [comment]
+1

**Comment by BartJanvanAssen** [comment]
any suggestions on this yet?

**Comment by harrishancock** [comment]
I think we can happily close this, as asynchronous HTMLRewriter handlers are now supported: https://community.cloudflare.com/t/2020-6-18-workers-runtime-release-notes/183460
