### ISSUE TITLE
Burst rate limit should be updated to 1000 requests per min

### ISSUE THREAD

**Issue by neynah** [cloudflare/workers-docs#457]
https://developers.cloudflare.com/workers/about/limits/

Burst rate limit currently says 1000 requests per 10 min, it should say 1000 requests per min.

![image](https://user-images.githubusercontent.com/855341/66936906-55f93e80-eff3-11e9-8061-8015c85eca85.png)

**Comment by signalnerve** [comment]
Closed by #458
