### ISSUE TITLE
Purge cache for cache API test/document behavior

### ISSUE THREAD

**Issue by exvuma** [cloudflare/workers-docs#474]
Test and then add documentation on cache purge. 

Cache purge should purge all a zone's cache including resources set by the Cache Api (maybe even for a key that doesn't match the zone..?)

Include Harris on the PR as reviewer

**Comment by harrishancock** [comment]
@adaptive, there's no `cache.purgeAll()` -- i.e., no way to purge the local colo's cache.

Regarding purge (from the dashboard or CF API) interaction with the Cache API, I would expect the following:
- Purge-by-URL works for any `url` (even if it doesn't match the zone) in the expression `caches.default.put(url, response)`.
  - Perhaps even if the response has a custom cache key? This would be a bug, though.
- Purge-by-tag works for any `response` so tagged in `cache.put(url, response)` (i.e., either `caches.default` or `caches.open(namespace)`).
- Purge-everything leaves all caches (`caches.default` or `caches.open(namespace)`) completely empty.
- Bugs and edge cases.

**Comment by harrishancock** [comment]
Updated my comment to reflect that purge-by-URL is not supported -- I just learned this from the Cache team.
