### ISSUE TITLE
Workers KV API section missing list method

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/workers-docs#482]
The [Workers API section](https://developers.cloudflare.com/workers/reference/storage/api/#worker-api) is missing the [`list()` method](https://developers.cloudflare.com/workers/reference/storage/listing-keys/).

A short TL;DR with a "see more" link to the main page would help, since a complete list of the in-worker methods would be in one place.

I'm happy to write up a short PR if there's interest :)

**Comment by signalnerve** [comment]
cc @steveklabnik

**Comment by steveklabnik** [comment]
Yep, this would be good to fix. We do have plans for a complete re-fresh of the API docs but don't know when that's scheduled (@ashleygwilliams).  A PR in the meantime would be great though!
