### ISSUE TITLE
Add a template for react SSR app.

### ISSUE THREAD

**Issue by resdevd** [cloudflare/workers-docs#490]
There is no template available regarding react SSR in Cloudflare workers.
Hoping there is way to deploy serverless app via Cloudflare workers for server side rendering.
What would be best choice of tool?  Nextjs or helmet with parcel? 
What would be the best way to implement react SSR ?

**Comment by nodebotanist** [comment]
I'll submit a PR with a template for this by the end of this week.

**Comment by victoriabernard92** [comment]
Moved to registry https://github.com/victoriabernard92/template-registry/issues/13
