### ISSUE TITLE
Add DNS and SSL preferred settings for Cloudflare Worker sites.

### ISSUE THREAD

**Issue by resdevd** [cloudflare/workers-docs#491]
When using wrangler publish DNS can be empty? 
SSL mode should be Full instead of Full (Strict)?
Any other recommended settings when deploying purely via Cloudflare Worker sites?

Bdw this is the game changer of front end deployment I've even encountered. Thanks for the great service.

**Comment by adaptive** [comment]
related to #251

For "deploying purely via Cloudflare Worker sites" SSL mode is not relevant as there is not `fetch()` to a origin server.

**Comment by victoriabernard92** [comment]
This is a duplicate so closing. Thanks for the feedback fixing this soon :)
