### ISSUE TITLE
Misrendered Response API

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/workers-docs#492]
Note the issue with `Body` formatted:
![image](https://user-images.githubusercontent.com/9408157/67809231-57504f80-fa66-11e9-96c5-44d9c702f13f.png)
https://developers.cloudflare.com/workers/reference/apis/response/
scroll to methods

`Body` should be it's own paragraph with its methods as an unordered list. It should be a simple markdown fix.

**Comment by adaptive** [comment]
pull request #493 sorts it.
the issue also extended to Parameters on the same page.
