### ISSUE TITLE
Revise quickstart to use API tokens and not API keys

### ISSUE THREAD

**Issue by victoriabernard92** [cloudflare/workers-docs#519]
Quickstart should guide users through using API tokens 

https://chat.google.com/room/AAAAC8J0m_Q/RvAt3q3q9MA

**Comment by signalnerve** [comment]
happy to pick this up, will put it on my todos for the back half of the month

**Comment by gabbifish** [comment]
It would be awesome to have guides for both 
1. where to find api keys for use
1. where to find tokens for use :D 
@ashleymichal and I stumbled upon that here: https://github.com/cloudflare/wrangler/pull/842
