### ISSUE TITLE
Integrate template page with tutorial content 

### ISSUE THREAD

**Issue by exvuma** [cloudflare/workers-docs#528]
### Old format 
notice change on 2nd paragraph: 
![image](https://user-images.githubusercontent.com/7578652/68698576-d0f83b00-0546-11ea-8df1-2b96b6318a60.png)

### NEW Format
![image](https://user-images.githubusercontent.com/7578652/68711505-5d165c80-055f-11ea-96cd-b0e0b3dbbe15.png)
 More detailed design [on figma](https://www.figma.com/file/znehQie47hTdaMnvH8njkN/Workers-Designs-Q4---Config-V%2C-Storage%2C-Ent?node-id=513%3A0)

From TODOs on https://github.com/cloudflare/workers-docs/pull/515, apply the redesigns of the template page integrated with a `.md` file template as in Router instance.

**Comment by signalnerve** [comment]
hey @victoriabernard92, is the change requested for this issue specifically around the tutorial content matching the CSS of the header/description? there's also some changes to the sidebar and the code blocks, does it cover that too? happy to do this but tbh it will probably end up being january milestone

**Comment by victoriabernard92** [comment]
I actually think we should wait until we are in Gatsby for this unassigned and tracked in that milestone. Very close 💃
