### ISSUE TITLE
Workflows can't be executed on this repository

### ISSUE THREAD

**Issue by adaptive** [cloudflare/workers-docs#537]
Billing configuration issue on `cloudflare/workers-docs`
- Workflows can't be executed on this repository. Please check your payment method or billing status.

<img width="438" alt="Screen Shot 2019-11-15 at 23 34 15" src="https://user-images.githubusercontent.com/17833/68982893-9a4d4980-0800-11ea-9c63-eff7182daf4c.png">

**Comment by victoriabernard92** [comment]
This is a known issue Cloudflare DX team is actively working to fix. Thanks for calling this out @adaptive we are tracking internally so closing this
