### ISSUE TITLE
Document new Cache.put() limits

### ISSUE THREAD

**Issue by harrishancock** [cloudflare/workers-docs#564]
Need to update https://developers.cloudflare.com/workers/about/using-cache/.

The new limits are 5GiB per eyeball request and 5GiB per Cache.put() (regardless of whether it's a Content-Encoding or Transfer-Encoding: chunked response). However, the per-put limit is also restricted by our regular cache limits: https://support.cloudflare.com/hc/en-us/articles/200172516-Understanding-Cloudflare-s-CDN

**Comment by adaptive** [comment]
@harrishancock, will it change to?

For Free, Pro, Business:
5GBs total put() per-request
up to 512MB for each put() with a valid Content-Length header
up to 512MB for a put() with Transfer-Encoding: chunked. Note that this blocks subsequent put()s until the transfer completes.

For Enterprise:
5GBs total put() per-request
up to 5GBs for each put() with a valid Content-Length header
up to 5GBs for a put() with Transfer-Encoding: chunked. Note that this blocks subsequent put()s until the transfer completes.

> https://support.cloudflare.com/hc/en-us/articles/200172516-Understanding-Cloudflare-s-CDN
The maximum file size Cloudflare's CDN caches is 512MB for Free, Pro, and Business customers and 5GB for Enterprise customers. Enterprise customers can contact their Cloudflare Account Team to request caching of larger files.

**Comment by harrishancock** [comment]
Yes, exactly.

**Comment by harrishancock** [comment]
Note: this change is now live.
