### ISSUE TITLE
Video "archived"/not available on Wrangler CLI page

### ISSUE THREAD

**Issue by neynah** [cloudflare/workers-docs#576]
https://developers.cloudflare.com/workers/tooling/wrangler/

![image](https://user-images.githubusercontent.com/855341/70485060-b6ac7100-1aa2-11ea-9354-0cd24eff5a6e.png)

**Comment by signalnerve** [comment]
ah! cc @EverlastingBugstopper, we may need to re-upload the asciicast and tie it to a user account

**Comment by victoriabernard92** [comment]
dup of #562
