### ISSUE TITLE
[Request] Wildcard in the middle of a domain

### ISSUE THREAD

**Issue by jeanpoelie** [cloudflare/workers-docs#583]
Hello,

Is it possible for you to add a wildcard in the middle of a domain.
We run domains like `stage-[api].[domain].com` and want to run 1 webworker per enviroment,
Right now we need to have 5-10 workers per domain instead of running just 1.

Accoring to the documentation, and the working of the website, we can only add wildcards at the start or at the end.

Documentation:
https://developers.cloudflare.com/workers/about/routes/#matching-behavior

Github location:
https://github.com/cloudflare/workers-docs/edit/master/content/about/routes.md

**Comment by ashleymichal** [comment]
the documentation is accurate, unfortunately. depending on your use case, you can either:

1. configure multiple route patterns on the same worker (in-UI only until 1.7.0, track progress on [this milestone](https://github.com/cloudflare/wrangler/milestone/19) for support in wrangler). 

2. branch off the URL inside your worker(s).

**Comment by jeanpoelie** [comment]
I understand the documentation is correct but I would like to be able to add a wildcard in the middle of domain, this seems to me like standard practise.

**Comment by ashleymichal** [comment]
Understood! Thank you for the feedback; I can raise this in the larger conversation around route definitions in the Workers platform, however the feature cannot be addressed in this repository and so I'm going to close this issue for now. I have linked this issue in an internal document aggregating user feedback about routing in Workers.
