### ISSUE TITLE
entry-point documentation of worker site is inconsistent / wrong

### ISSUE THREAD

**Issue by minddust** [cloudflare/workers-docs#607]
### 🐛 Bug Report

The `entry-point` attribute for the worker site is optional and has a default of `workers-site`:

https://github.com/cloudflare/wrangler/blob/master/src/settings/toml/site.rs#L32

It's the same what the docs are stating, but although it has a default it's marked as `required=true` which is false ;) 

https://developers.cloudflare.com/workers/tooling/wrangler/sites/

Not sure if this is the right place to report this cause it's not part of the code base 🤷‍♂

**Comment by signalnerve** [comment]
@minddust thanks for filing an issue! happy to look at a PR if you want to open one, otherwise I can get it tagged/labeled for us to pick up sometime soon :)
