### ISSUE TITLE
Routes with Multiple Workers

### ISSUE THREAD

**Issue by juanmrad** [cloudflare/workers-docs#612]
It would be good to have more information on how you can have multiple workers apply to the same route or multiple routes. and what kind of priority there is.

i.e. I have a worker for the route `*.example.com* ` that does something specific, but also a worker for the route `*.example.com/path*` which fetches the response somewhere else. 

Which worker will trigger one or both. and what is the order from them.

From what I've tested on the playground it looks like if the first main worker does:

`  return fetch(request);`

It will transform the request and pass it along to the next worker to handle the rest. else the more broad worker will handle and return skipping the more specific worker. 

Not sure if this is 100% accurate or not and would be good to have it documented.

**Comment by ashleymichal** [comment]
this is a weird one to document, as this is one of the places where playground behavior does not represent production behavior. there are technical reasons why this discrepancy exists, but the bottom line is that at this time only a single worker is executed on each request, and when two routes match the incoming request, the more specific route pattern will "win". 

Any other sub-request made to a url on the same zone is treated as a request directly to the origin server, while requests made to urls on other zones are treated as requests back out to the internet, so in theory you could trigger another worker with a sub-request _if it is on a different zone_.

Where would you go looking for this information first? We have some things about routes documented but perhaps they are not as discoverable as they could be.

**Comment by juanmrad** [comment]
I'm trying to look for information on the routes docs. and then try to tested on the playground. I was going to deploy something with just a simple console.log to see how the behavior was like in production without doing any actual changes to the request itself.

**Comment by victoriabernard92** [comment]
This is documented in [Fetch Event Life cycle](https://developers.cloudflare.com/workers/about/tips/fetch-event-lifecycle/#body-inner)
```
If a fetch event handler does not call respondWith(), the runtime delivers the event to the next registered fetch event handler. If no event handler calls respondWith(), the runtime proxies the request to the origin. Note: If no origin is setup (always true for workers.dev sites), then you must have a respondWith() called for a valid response.
```
We realize it's not so clear how to navigate to this section. We are actually working on making the explanation/about articles like this more clear to get to and clean up the language in the future. I appreciate your feedback.
