### ISSUE TITLE
Clarification regarding Workers' place in the request life-cycle

### ISSUE THREAD

**Issue by abiro** [cloudflare/workers-docs#631]
Hi,

it's not so clear from the documentation where a Worker is executed in the request life-cycle. My best understanding currently is this:

```
client => CF edge => CF security rules => CF worker => CF cache => ??? => origin

client <= CF edge <= CF cache <= ??? <= origin
```

Is this correct? (A figure similar to [this](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-cloudfront-trigger-events.html) from the Lambda@Edge docs would be super helpful.)

Thanks,
Agost

**Comment by signalnerve** [comment]
cc @rita3ko maybe on how/where we should document this

**Comment by rita3ko** [comment]
feels related to / like it should be a part of https://developers.cloudflare.com/workers/about/how-it-works/
