### ISSUE TITLE
previewing with wsl instructions broken

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/workers-docs#640]
![image](https://user-images.githubusercontent.com/9408157/73675682-82a39580-4678-11ea-9967-405008e93014.png)

The anchor link at the top is also broken

**Comment by ispivey** [comment]
Wanted to clarify what's broken here:

To repro:
* Navigate to https://developers.cloudflare.com/workers/tooling/wrangler/commands/
* Click on "Making it work with WSL"

Observe the anchor link is broken.

Additionally, Markdown inline code annotation is missing from the second `eg.` in the screenshot above, on that page.

**Comment by EverlastingBugstopper** [comment]
thanks ian - initial report was not super clear :)
