### ISSUE TITLE
Please document cache key format

### ISSUE THREAD

**Issue by johnelliott** [cloudflare/workers-docs#655]
Hi, enterprise customer here; been building out a project with workers for a few months.

The documentation regarding the cache keys format is incorrect. For example, this worker code produces an error:
```javascript
const k = `::${new URL(event.request)}`;
const cacheKeyMatch = await caches.default.match(k);
```
Here's some of the errors this produced today: `TypeError: Invalid URL string.`
As of a few days ago the error was: `TypeError: Invalid URL. Cache API keys must be fully-qualified, valid URLs.`

I am creating a PR <https://github.com/cloudflare/workers-docs/pull/656> that updates documentation about cache keys to note that the current key format must be a valid URL, but doesn't do much more.

Still needed from Cloudflare staff is information the cache key format and how setting one interacts with page rules. Currently it's unclear how to use cache keys in workers.

**Comment by harrishancock** [comment]
Hi @johnelliott,

`cache.match()` accepts either a valid URL or a Request object as its first argument. A Request object may have a custom cache key. So, to use a custom cache key with the Cache API, the syntax would be something like

```js
const k = `::${new URL(event.request)}`
const request = new Request(event.request, { cf: { cacheKey: k } })
const cacheKeyMatch = await caches.default.match(request)
```

However, I've never tested that, so I'm not sure if it works as written.

**Comment by johnelliott** [comment]
> Hi @johnelliott,
> 
> `cache.match()` accepts either a valid URL or a Request object as its first argument. A Request object may have a custom cache key. So, to use a custom cache key with the Cache API, the syntax would be something like
> 
> ```js
> const k = `::${new URL(event.request)}`
> const request = new Request(event.request, { cf: { cacheKey: k } })
> const cacheKeyMatch = await caches.default.match(request)
> ```
> 
> However, I've never tested that, so I'm not sure if it works as written.

Thanks @harrishancock, I will try and post my result here tomorrow.

**Comment by johnelliott** [comment]
Thanks for following up with me @harrishancock.

The confusion is on my end. I think the confusion originated from reading <https://github.com/cloudflare/workers-docs/blob/master/content/archive/reference/cache-api.md#caching-post-requests> where the URL is named `cacheKey`. Then seeing the `cacheKey` of the `cf` object being any string, I thought any string could work as an argument to `caches.Match()`.

Here's that snippet:
```javascript
    // Convert to a GET to be able to cache
    let cacheKey = new Request(url, {headers: request.headers, method: 'GET'})

    let cache = caches.default
    //try to find the cache key in the cache
    response = await cache.match(cacheKey)

    // otherwise, fetch from origin
    if (!response) {
      // makes POST to the origin
      response = await fetch(request.url, newRequest)
      event.waitUntil(cache.put(cacheKey, response.clone()))
    }
```

I'd be happy to update the docs. Perhaps that could be renamed so the only references to `cacheKey` are related to the cache API. Would that make sense to do?

**Comment by harrishancock** [comment]
Hi @johnelliott, I think you're absolutely right: using `cacheKey` as a variable identifier in example code risks confusion with the Request constructor's `cf.cacheKey` option.

> Perhaps that could be renamed so the only references to cacheKey are related to the cache API.

I think we'll have to do it the other way around: any references to `cacheKey` should refer exclusively to the Request constructor's option, if possible, since it's not feasible for us to rename the Request constructor option. We should probably use some generic name like `req`, `request`, or `url` for variables in Cache API example code.

If you do have time/energy to submit a PR, we'd certainly appreciate it! If not, I'll get to it -- I'm pretty sure I'm the one who wrote the confusing code to begin with. :|

**Comment by johnelliott** [comment]
> I think we'll have to do it the other way around: any references to `cacheKey` should refer exclusively to the Request constructor's option, if possible, since it's not feasible for us to rename the Request constructor option. We should probably use some generic name like `req`, `request`, or `url` for variables in Cache API example code.

Yes, this is what I was thinking too. I didn't mean to make it sound the other way around.

**Comment by johnelliott** [comment]
Hi @harrishancock, I added a PR for this name change here: <https://github.com/cloudflare/workers-docs/pull/665>
