### ISSUE TITLE
Add to Security page best practices?

### ISSUE THREAD

**Issue by tomByrer** [cloudflare/workers-docs#659]
EG to the [security](https://developers.cloudflare.com/workers/about/security/#body-inner) article add how to add 2FA, watch results in various browsers, search results, etc.

Reasoning; comprised accounts can become spam bots:
https://blog.sucuri.net/2020/02/abused-cloudflare-workers-service-used-to-inject-korean-seo-spam.html?utm_source=twitter&utm_medium=blog&utm_campaign=wyatt

**Comment by signalnerve** [comment]
cc @rita3ko
