### ISSUE TITLE
Provided example of webpack.development.js causes EvalError on publish

### ISSUE THREAD

**Issue by bdunlap** [cloudflare/workers-docs#682]
Not sure if this is an environment-specific problem but I am just getting started with Workers and was following the [Webpack instructions](https://developers.cloudflare.com/workers/tooling/wrangler/webpack/) and got an EvalError when running `wrangler publish`.

Turns out I needed to explicitly specify a devtool that doesn't use eval. This is discussed [here](https://github.com/cloudflare/workers-webpack-example/issues/1) but I suspect that repo is now obsolete. 

The problem doesn't occur until you provide your own webpack config file and copy the example from the Workers docs. The fix (or at least 'a' fix) is to add `"devtool": "cheap-module-source-map"` to `module.exports` in webpack.development.js.

**Steps to reproduce:**

1. Install and configure wrangler [as described in Quickstart](https://developers.cloudflare.com/workers/quickstart)
2. Create a project from an official template that uses webpack; e.g., `wrangler generate eval-error https://github.com/cloudflare/worker-template-router`
3. Edit `wrangler.toml`: populate `account_id` and add `webpack_config = "webpack.development.js"`
4. Create `webpack.development.js` with contents shown in [Webpack instructions](https://developers.cloudflare.com/workers/tooling/wrangler/webpack/)
5. Run `wrangler publish`

**Results (with node 10.16.2 and npm 6.14.2):**

Deploy fails with:
```
Error: Something went wrong! Status: 400 Bad Request, Details {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10021,
      "message": "Uncaught EvalError: Code generation from strings disallowed for this context\n  at line 96 in ./index.js\n  at line 20 in __webpack_require__\n  at line 84\n  at line 87\n"
    }
  ],
  "messages": []
}
```

**Comment by bdunlap** [comment]
Just submitted PR #683

**Comment by victoriabernard92** [comment]
Closed by the PR thanks @bdunlap
