### ISSUE TITLE
Broken link in template gallery for "Modify Request Property" snippet

### ISSUE THREAD

**Issue by ispivey** [cloudflare/workers-docs#690]
Reported to me by someone else who doesn't have a github account:

> Some of the links on https://developers.cloudflare.com/workers/templates/ are not loading properly, and prevent navigation. The example I've noted today is "Modify request property" which has `https://templates/snippets/modify_req_props` as the URL.

![image-2020-03-10-16-22-25-961](https://user-images.githubusercontent.com/99628/76442815-786b6a00-638f-11ea-9b16-bb486feaf093.png)

**Comment by victoriabernard92** [comment]
This no longer happens, I don't remember when this got fixed to be honest. My apologies for not closing then 
<img width="681" alt="Screen Shot 2020-04-28 at 9 56 09 AM" src="https://user-images.githubusercontent.com/7578652/80502663-891f7180-8936-11ea-86aa-c0039f4f2ad1.png">
