### ISSUE TITLE
"Build a Serverless Function" doesn't work when using `wrangler dev` or `wrangler publish`

### ISSUE THREAD

**Issue by jarrodldavis** [cloudflare/workers-docs#700]
I've gone through the [Build a Serverless Function tutorial][tutorial] and I can't get `wrangler dev` or `wrangler publish` to work. Both commands result in an error stating that `require` is not defined, leading me to believe there is a build step that is needed but not mentioned in the tutorial.

<details>
<summary>`wrangler dev`</summary>

```sh
❯ wrangler dev
      ┌────────────────────────────────────────────────────────────────────────────────────────────┐
      │                                                                                            │
      │      wrangler dev is currently unstable and there are likely to be breaking changes!       │
      │    For this reason, we cannot yet recommend using wrangler dev for integration testing     │
      │    Please submit any feedback here: https://github.com/cloudflare/wrangler/issues/1047     │
      │                                                                                            │
      └────────────────────────────────────────────────────────────────────────────────────────────┘

💁  JavaScript project found. Skipping unnecessary build!
👂  Listening on http://localhost:8787
💁  watching "./"
Uncaught
ReferenceError: require is not defined
    at worker.js:1:12
[2020-03-16 18:12:44] GET example.com/ HTTP/1.1 200 OK
```

</details>

<details>
<summary>`wrangler publish`</summary>

```sh
$ wrangler publish
💁  JavaScript project found. Skipping unnecessary build!
Error: Something went wrong! Status: 400 Bad Request, Details {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10021,
      "message": "Uncaught ReferenceError: require is not defined\n  at line 1\n"
    }
  ],
  "messages": []
}
```

</details>

[tutorial]: https://developers.cloudflare.com/workers/tutorials/build-a-serverless-function

**Comment by jarrodldavis** [comment]
Okay, I was able to solve this issue by following the instructions under [Tooling > Wrangler CLI > webpack][webpack], namely changing `wrangler.toml`:

```diff
diff --git a/wrangler.toml b/wrangler.toml
index 674654e..b3b20cb 100644
--- a/wrangler.toml
+++ b/wrangler.toml
@@ -1,5 +1,5 @@
 name = "cloudflare-workers-qr-code-generator"
-type = "javascript"
+type = "webpack"
 account_id = ""
 workers_dev = true
 route = ""
```

Perhaps this should be mentioned in the [Serverless][serverless] and [Application][application] tutorials?

[webpack]: https://developers.cloudflare.com/workers/tooling/wrangler/webpack/
[serverless]: https://developers.cloudflare.com/workers/tutorials/build-a-serverless-function
[application]: https://developers.cloudflare.com/workers/tutorials/build-an-application

**Comment by signalnerve** [comment]
Documented this in the example codebase - https://github.com/signalnerve/workers-qr-code-generator - will make sure this makes it into the tutorial too. Thanks!
