### ISSUE TITLE
Search on template gallery doesn't work

### ISSUE THREAD

**Issue by signalnerve** [cloudflare/workers-docs#702]
After migrating to Gatsby in the docs, the search behavior on the Template Gallery page seems to have been degraded. Typing in the search field and then emptying the field doesn't re-render the full set of templates. There may be other issues as well, but this was the immediate one filed in our internal chat.

https://developers.cloudflare.com/workers/templates/

**Comment by ispivey** [comment]
@victoriabernard92 can you take a look, since this was a regression after #616 ?
