### ISSUE TITLE
Modifying request link broken

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/workers-docs#705]
https://developers.cloudflare.com/workers/reference/apis/request/ links to https://developers.cloudflare.com/workers/templates/snippets/modify_req_props/ which no longer exists (i think it probably should)

edit: looks like it should link here: https://developers.cloudflare.com/workers/templates/pages/modify_req_props/

**Comment by ispivey** [comment]
I just checked, and this is fixed.
