### ISSUE TITLE
Broken links on Template Gallery page

### ISSUE THREAD

**Issue by martijngonlag** [cloudflare/workers-docs#707]
Various templates on the [Template Gallery](https://developers.cloudflare.com/workers/templates/) page are leading to 404s or entirely incorrect URLs. 

**Steps to reproduce**
1. Navigate to https://developers.cloudflare.com/workers/templates/
2. Click on "Router" under "Boilerplates"
3. Observe 404

**Examples of broken links**
* Router
* Cloud Storage: `https://developers.cloudflare.com/workers/templates/featured_boilerplates/cloud_storage`
* Graphql: `
https://developers.cloudflare.com/workers/templates/featured_boilerplates/graphql`
* Aggregate Requests: `https://templates/snippets/aggregate_requests`
* Signed Requests: `https://templates/snippets/signed_request`

**Comment by victoriabernard92** [comment]
Thanks for thoroughly bug report @martijngonlag all fixed https://github.com/cloudflare/workers-docs/pull/708

**Comment by victoriabernard92** [comment]
Fixed now hard refresh in your browser to check
