### ISSUE TITLE
Any documentation on how to create a "text_blob" binding like Wrangler Does?

### ISSUE THREAD

**Issue by nickreese** [cloudflare/workers-docs#729]
[This document](https://developers.cloudflare.com/workers/tooling/api/bindings/) appears to be missing how to use the "text_blob" binding that Wrangler uses to generate the `__STATIC_CONTENT_MANIFEST`.

The relevant code in wrangler is here: https://github.com/cloudflare/wrangler/blob/master/src/upload/form/mod.rs#L144

Below is the code I'm hitting the API with. I get an error of `could not read content for part`

```
  const metadata = {
    body_part: 'script',
    bindings: [
      {
        name: '__STATIC_CONTENT_MANIFEST',
        type: 'text_blob',
        part: JSON.stringify(manifest),
      },
    ],
  };

  form.append('metadata', `${JSON.stringify(metadata)}`, { contentType: 'application/json' });
  form.append('script', fs.readFileSync(path.resolve(__dirname, './worker/script.js'), { contentType: 'application/javascript' }));
  const r = await axios.put(`https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_IDENTIFIER}/workers/scripts/${namespace.script}`, form, {
    headers: { ...form.getHeaders(), 'X-Auth-Email': CF_EMAIL, 'X-Auth-Key': CF_API_KEY },
  });

```

I've tried storing it as a text binding but it is too long. 

Having the ability to use a text_blob appears to also be a requirement for using this package: https://github.com/cloudflare/kv-asset-handler

**Comment by signalnerve** [comment]
cc @ashleymichal

**Comment by nickreese** [comment]
Sorted it out.

I needed to add another form field to match the "part" name given.

```
  const metadata = {
    body_part: 'script',
    bindings: [
      {
        name: '__STATIC_CONTENT_MANIFEST',
        type: 'text_blob',
        part: 'text_blob',
      },
    ],
  };

  form.append('metadata', `${JSON.stringify(metadata)}`, { contentType: 'application/json' });
  form.append('script', fs.readFileSync(path.resolve(__dirname, './worker/script.js'), { contentType: 'application/javascript' }));
  form.append('text_blob', JSON.stringify(manifest), { contentType: 'text/plain' });

  const r = await axios.put(`https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_IDENTIFIER}/workers/scripts/${namespace.script}`, form, {
    headers: { ...form.getHeaders(), 'X-Auth-Email': CF_EMAIL, 'X-Auth-Key': CF_API_KEY },
  });
```

As far as the docs. 

Overall the worker docs are really good. As @ashleymichal probably knows I'm working to overcome the 10k limit in Wrangler without knowing Rust. lol.

That said, if I can give some constructive feedback on the [upload documentation](https://developers.cloudflare.com/workers/tooling/api/scripts/#upload-or-update-a-workers-script-with-resource-bindings), I'd say that a complete example in curl (or any language) would help help make it more obvious that the form needs the to have a field to match the binding in the metadata object.

Thanks for all you guys do. You're rockstars.
