### ISSUE TITLE
Link to support not properly displayed

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/workers-docs#747]
https://developers.cloudflare.com/workers/archive/writing-workers/debugging-tips/ 

```
Workers runtime itself -- please [raise a support ticket](https://support.cloudflare.com/hc/en-us/requests/new) if you see one.
```

**Comment by victoriabernard92** [comment]
Ugg shame on me for not seeing this! Nice catch Avery

**Comment by victoriabernard92** [comment]
Oh just kidding this is in archive, we don't plan on maintaining this forever. But we should make sure that the archive link instead redirects to /workers/about/tips/debugging/
