### ISSUE TITLE
In Template detail pages, "Run in your terminal" copy-box container is too narrow

### ISSUE THREAD

**Issue by ispivey** [cloudflare/workers-docs#749]
On template detail pages like https://developers.cloudflare.com/workers/templates/pages/router , the contents of the "Run in your terminal" terminal snippet is illegible because the container is too narrow and the container seems to be set to `overflow:scroll`, causing (a) the contents of the container to be obfuscated by scrollbars on some browsers (e.g. Chrome) and (b) most of the content to not be visible without scrolling.

![Screen Shot 2020-04-24 at 3 32 24 PM](https://user-images.githubusercontent.com/99628/80254461-d4890580-8640-11ea-8b2d-5a7735128171.png)

I don't have a specific suggestion as to the right CSS 🧙‍♀️  to address this or the exact desired behavior, but we likely want the container size to flex in width/height as space permits. Like this-ish, but without the dangling copy box:

![Screen Shot 2020-04-24 at 3 22 08 PM](https://user-images.githubusercontent.com/99628/80254310-90960080-8640-11ea-94b2-9793bd7d7fef.png)

**Comment by victoriabernard92** [comment]
Thanks for looking into that Ian and even providing a well thought out potential solution! I think UI + the content of this page is what's confusing the goal.

CTAs for this box are: copy paste that command and/or peak the code at the github URL. The intention was **not** to have users peak inside the content of the `wrangler generate` command so much.

I 💯 agree this looks odd and the intention of the page directs user eyeballs to do exactly what you did: want to examine the inside of that box. If there was more content on that page (i.e.. router had a how-to article along with it or even a snippet) then the attention wouldn't go so much into examining that box.

Ideas for solving the problem without changing the goal CTAs:
* fix the CSS so the box stays on the RHS
* expand the content of snippets (prioritizing our most popular such as router) so the box isn't such a distraction that users frustratingly want to peak into

**Comment by ispivey** [comment]
Ooh, good points.

Without re-examining the intended design of the page, it seems reasonable to improve this by changing CSS to move the "run in your terminal" box to the RHS if that's the intended design.

As a user, I'd like to know what I'm copy-pasting before I copy-paste it, which is why I'd rather not have that `overflow:scroll` – but happy to defer that discussion for later.
