### ISSUE TITLE
Restore code syntax highlighting

### ISSUE THREAD

**Issue by ispivey** [cloudflare/workers-docs#753]
We previously supported syntax highlighting for code samples, which helps readability. It appears that after the Gatsby migration in #616, we no longer have syntax highlighting. We should restore it! I'm not sure if this is missing functionality in our Gatsby build (I suspect it is) or an issue with our Markdown files.

Forgive me if this is already filed – couldn't find it when searching the issues.

Before:
![localhost_1313_workers_tutorials_manage-projects-with-lerna_(iPad Pro)](https://user-images.githubusercontent.com/99628/80283564-11efa080-86de-11ea-8887-5638dfacc496.png)

After:
![developers cloudflare com_workers_tutorials_manage-projects-with-lerna(iPad Pro)](https://user-images.githubusercontent.com/99628/80283570-1ae07200-86de-11ea-9213-d8937dd0c158.png)

**Comment by victoriabernard92** [comment]
Was holding off on the redesign to mess with syntax highlighting. @adamschwartz  was syntax highlighting something you're been looking into yet?

**Comment by ispivey** [comment]
@victoriabernard92 I think it’s worth seeing if you can get syntax highlighting back with a pretty naive/vanilla implementation of https://www.gatsbyjs.org/packages/gatsby-remark-prismjs/ rather than blocking on the redesign work. It should be pretty straightforward, and would be valuable to users to get that back soon. Happy to talk about it more, though.

**Comment by ispivey** [comment]
This seems to be broken again.
