### ISSUE TITLE
Broken link from "Rewrite Links in HTML" template to HTMLRewriter docs

### ISSUE THREAD

**Issue by ispivey** [cloudflare/workers-docs#760]
The [Rewrite Links in HTML template](https://developers.cloudflare.com/workers/templates/pages/rewrite_links_html/) links to the HTMLRewriter docs, but the link is broken.

Link is to: https://developers.cloudflare.com/reference/apis/html-rewriter
Should be to: https://developers.cloudflare.com/workers/reference/apis/html-rewriter

**Comment by victoriabernard92** [comment]
This issue is actually fixed in https://github.com/cloudflare/workers-docs/pull/763 through `MDXwithComponenets`
