### ISSUE TITLE
Document botManagement property of request.cf

### ISSUE THREAD

**Issue by h-a-s-a-n** [cloudflare/workers-docs#775]
The [Bot Management](https://blog.cloudflare.com/cloudflare-bot-management-machine-learning-and-more/) properties are currently missing from the `Request` runtime API [documentation](https://developers.cloudflare.com/workers/reference/apis/request/).

**Comment by leftspace89** [comment]
still missing dude

**Comment by leftspace89** [comment]
oh found it.
