### ISSUE TITLE
Setting environment variables isn't clear. Also getting them is not clear.

### ISSUE THREAD

**Issue by teebu** [cloudflare/workers-docs#782]
https://developers.cloudflare.com/workers/reference/apis/environment-variables/

I found 3 different ways of setting them, but it's inconsistent and confusing. 

1. Setting in wrangler.toml: (this isn't documented anywhere, that I see)
```
vars = {ENV = "beta", TESTING = "testing string"}
```
Does set the variables, I can see it on the page:

![image](https://user-images.githubusercontent.com/5531844/81489303-bd453d00-9228-11ea-86fc-f5c0242ab995.png)

However calling them in my code, I get nothing back. 

In code:
```
  response.headers.set('x-testing', process.env.TESTING);
```
![image](https://user-images.githubusercontent.com/5531844/81489344-2036d400-9229-11ea-9538-dc9225c2d52c.png)

2. When deploying through CLI, while also using webpack.config.js - it actually works in the script, and takes priority over what the web ui variable shows. 

But if its not set in the toml, and only in the webpack, it works but it doesn't appear on the web ui. 

That is confusing.
```
const { EnvironmentPlugin } = require('webpack');

module.exports = {
  entry: './index.js',
  plugins: [
    new EnvironmentPlugin({
      TESTING: 'inwebpack',
    }),
  ],
};
```

``` TESTING=something wrangler publish```
![image](https://user-images.githubusercontent.com/5531844/81489370-6be97d80-9229-11ea-8b18-9ec08b8b68e7.png)

![image](https://user-images.githubusercontent.com/5531844/81489419-fd58ef80-9229-11ea-8ce6-5189064618f3.png)

3. Manually setting it on the web UI does nothing. I can't retrieve process.env.TESTING in my code. 

This article talks about secrets, but nothing about actual setting regular environment variables, or how to actually use them. https://blog.cloudflare.com/workers-secrets-environment/

So far, the only consistent thing is doing it directly though the webpack config, without touching the toml. But I'd like to try to do everything in the toml, and it's not clear how secrets work in the webpack config.

**Comment by signalnerve** [comment]
hey @teebu, thanks for the detailed bug report! in this case, anything you set as secrets/text variables via wrangler will be available as constants, importantly _without_ `process.env` - `URL` instead of `process.env.URL`. hope that helps!

**Comment by teebu** [comment]
Where is the actual documentation on how to set env variables?

**Comment by signalnerve** [comment]
@teebu the docs for using `wrangler secret` command can be found [here](https://developers.cloudflare.com/workers/tooling/wrangler/secrets/).

as for using anything from `wrangler secret` or the `vars` field in `wrangler.toml`, it's referred to via a constant.

e.g. `wrangler secret put TEST` creates a constant `TEST` in your code, `vars = { TEST2 = "val" }` creates a constant `TEST2`. 

the webpack/dotenv stuff isn't supported by the wrangler team/workers runtime, but it sounds like what it's probably doing is generating an object that simulates `process.env` - note that you're likely including those as a plaintext object in your code (something like `const process = { env: { TEST: 'val', TEST2: 'val2' } }`) and i'd strongly recommend using secrets in favor of that approach as any sensitive values won't be included as plaintext in your code.

**Comment by teebu** [comment]
You should add this `vars = { TEST2 = "val" }` to the docs somewhere, where its visible.
