### ISSUE TITLE
Broken image links on "Hosting Static Wordpress Sites" Tutorial

### ISSUE THREAD

**Issue by ispivey** [cloudflare/workers-docs#788]
To reproduce:
1. Navigate to https://developers.cloudflare.com/workers/tutorials
1. Click "Hosting Static WordPress Sites"
1. Observe broken image links for all embedded images

<img width="625" alt="Screen Shot 2020-05-12 at 8 33 31 AM" src="https://user-images.githubusercontent.com/99628/81698226-4a57e400-942b-11ea-975f-da761b576903.png">

In the Network tab, I note that a request for `https://developers.cloudflare.com/workers/tutorials/media/wordpress--install-plugin.png` gets a 301 response redirecting to `https://developers.cloudflare.com/workers`.

Strangely, if you navigate directly to https://developers.cloudflare.com/workers/tutorials/hosting-static-wordpress-sites, it displays the images as expected. I note that in that case, the browser makes a request for `https://developers.cloudflare.com/workers/tutorials/hosting-static-wordpress-sites/media/wordpress--install-plugin.png`, which is different from the image URL requested when you navigate to the page from a different page.

**Comment by victoriabernard92** [comment]
This has been broken since at least when we converted to Gatsby. I think best path forward is find and replacing all the links that use `media/*` -> `/tutorials/*` @signalnerve does this sound like a good approach or do you have any other suggestions?

**Comment by ispivey** [comment]
The thing that’s puzzling to me is: why does the page load the correct images if you navigate to it directly, but not if you navigate to it from another page within the docs?

**Comment by victoriabernard92** [comment]
I thiiiink it's because of Gatsby prefetching things. I don't think it's a bad idea to change the link for consistency's sake either way (the rest of the markdown file all use links starting with `/`). I am not sure if this ever worked in hugo either
