### ISSUE TITLE
Investigate if browserTTL is set too high and potentially forcing stale content of all assets (including HTML) to returning visitors

### ISSUE THREAD

**Issue by whatnickcodes** [cloudflare/workers-docs#796]
Thank you all for what you do with these docs. This repo is really cool too... Amazing project.

Maybe dumb question: When using the [KV Asset Mapper here](https://github.com/cloudflare/workers-docs/blob/d08037312dc2b7c0083d7e2db64664514af931e3/workers-docs/workers-site/src/main.js#L42) you are setting the Edge and Browser TTL To `1 year` (`31536000 seconds`):

```javascript
      body = await getAssetFromKV(event, {
        mapRequestToAsset: myMapRequestToAsset,
        cacheControl:{
          browserTTL: 31536000,
          edgeTTL: 31536000
        }
      })
```

KV Asset Mapper defaults are:

```javascript
let cacheControl = {
  browserTTL: null, // do not set cache control ttl on responses
  edgeTTL: 2 * 60 * 60 * 24, // 2 days
  bypassCache: false, // do not bypass Cloudflare's cache
}
```

When viewing the site with or without JavaScript, you get the same results. **The template is rendered.**  So if you pushed an update, even  if you purge Edge cache with Cloudflare, wouldn't people's via their browsers see stale content if they visited the site before?

Or, is there some sort of revalidation or Gatsby magic going on?

Just looking to see how this is done

Thanks!

**Comment by victoriabernard92** [comment]
@whatnickcodes Definitely a great question that I don't have a full answer to. One year is not even realistic for browser caching. I think we did this when we were doing some performance test. We should probably set this to an hour for HTML assets. Thanks for raising this issue, I'll keep it open until I have a clearer answer or a fix.

**Comment by whatnickcodes** [comment]
Ah, okay! Glad I'm not crazy and in ballpark here.

I am very far from being knowledgeable on caching. I was pulling my hair out over weekend trying to figure out how you all were pulling this off if some trick or something against my own project that has the same issue.

I'll update the title of the issue to reflect the new consideration.

Thanks and again super awesome code samples here. Appreciate your time
