### ISSUE TITLE
Broken image in “Hosting Static WordPress Sites” tutorial

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/workers-docs#845]
https://developers.cloudflare.com/workers/tutorials/hosting-static-wordpress-sites

![image](https://user-images.githubusercontent.com/154613/82947461-1bcf2280-9f6e-11ea-8863-71ce9e37db0b.png)

**Comment by victoriabernard92** [comment]
This is solved in #793. Which I would love a review on 🙏 @adamschwartz  @signalnerve  Closing this issue
