### ISSUE TITLE
Document Analytics API

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/workers-docs#88]

**Comment by victoriabernard92** [comment]
Closing because this should be in api.cloudflare.com. Opened up the conversation in Workers Team chat as to why this is not there, will open Jira if need to add 
https://chat.google.com/room/AAAAAzbdxGI/qJB70p-Z9kw

**Comment by victoriabernard92** [comment]
Tracked at https://jira.cfops.it/browse/EW-2439
