### ISSUE TITLE
unify "required/optional" columns in tables

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/workers-docs#907]
across the docs, there are a bunch of fields that we document as required or optional. they're usually in tables, and the column names are sometimes "optional" and sometimes "required", and the contents of the column can be "y/n" or "optional/required"

we should make it so that all of these columns use the same format. would probably be good to have some sort of style guide as well as this is not the only inconsistent design

**Comment by nandanv2702** [comment]
Hey, do you mind if I work on this issue? I looked over the docs and plan on replacing all such columns with the header 'Required' and column contents with 'Yes' or 'No' depending on the situation.

**Comment by EverlastingBugstopper** [comment]
cc @adamschwartz and @signalnerve - are we taking contributions on this repo right now?

**Comment by adamschwartz** [comment]
cc @ispivey @rita3ko

**Comment by nandanv2702** [comment]
Hey, any update on this?

**Comment by rita3ko** [comment]
hi @nandanv2702 ! we're actually in the process of porting our docs over to a new system — (stay tuned for announcements), but would love your contribution in our new repo: https://github.com/cloudflare/workers-docs-engine
thanks!!

**Comment by nandanv2702** [comment]
@rita3ko Thank you so much for your reply! I'll definitely look over the new repo and contribute. Love what y'all do at Cloudflare!
